set(bridge "${dobby_SOURCE_DIR}/source/TrampolineBridge/ClosureTrampolineBridge/x64/closure-bridge-x64.cc")
file(READ "${bridge}" content)
if(NOT content MATCHES "V8_KILLER_WINDOWS_ENTRY")
  string(REPLACE "  // prepare args" "#if defined(_WIN32)\n  // V8_KILLER_WINDOWS_ENTRY: function entry has RSP = 8 mod 16; the saved context aligns it.\n  _ mov(rcx, rsp);\n  _ mov(rdx, Address(rsp, 8 + 8 + 16 * 8 + 2 * 8));\n  _ sub(rsp, Immediate(32, 32));\n  _ CallFunction(ExternalReference((void *)intercept_routing_common_bridge_handler));\n  _ add(rsp, Immediate(32, 32));\n#else\n  // prepare args" content "${content}")
  string(REPLACE "  // ======= RegisterContext Restore" "#endif\n  // ======= RegisterContext Restore" content "${content}")
  file(WRITE "${bridge}" "${content}")
endif()
set(globals "${dobby_SOURCE_DIR}/cmake/Globals.cmake")
file(READ "${globals}" content)
string(REPLACE "if(PROCESSOR.AARCH64 OR PROCESSOR.ARM)" "if(PROCESSOR.ARM)" content "${content}")
string(REPLACE "elseif(PROCESSOR.X86 OR PROCESSOR.X86_64)" "elseif(PROCESSOR.X86 OR PROCESSOR.X86_64 OR PROCESSOR.AARCH64)" content "${content}")
file(WRITE "${globals}" "${content}")

set(windows "${dobby_SOURCE_DIR}/source/UserMode/UnifiedInterface/platform-windows.cc")
file(READ "${windows}" content)
if(NOT content MATCHES "PAGE_READWRITE")
  string(REPLACE "else if (kReadExecute == access)" "else if (kReadWrite == access)\n    return PAGE_READWRITE;\n  else if (kReadExecute == access)" content "${content}")
endif()
file(WRITE "${windows}" "${content}")

set(build_file "${dobby_SOURCE_DIR}/CMakeLists.txt")
file(READ "${build_file}" content)
string(REPLACE "string(TIMESTAMP TODAY \"%Y%m%d\")" "set(TODAY \"20210615-223aabced043\")" content "${content}")
file(WRITE "${build_file}" "${content}")
