[package]
name = "v8_killer_core"
version.workspace = true
edition.workspace = true
authors.workspace = true

[lib]
crate-type = ["cdylib"]

[dependencies]
ctor = "1.0.13"
regex = "1.13.1"
serde = { version = "1.0.229", features = ["derive"] }
toml = "1.1.6"
tracing = { workspace = true }
tracing-subscriber = { workspace = true, features = ["env-filter"] }

[build-dependencies]
cmake = "0.1.58"

[target.'cfg(target_os = "windows")'.dependencies]
windows-sys = { version = "0.61.2", features = [
    "Win32_Foundation",
    "Win32_System_Console",
] }
