on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'docs/**'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - 'docs/**'

name: Test

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - name: Run non-macOS tests
        if: matrix.os != 'macos-latest'
        run: cargo test --verbose

      - name: Run macOS tests
        if: matrix.os == 'macos-latest'
        run: |
          rustup target add aarch64-apple-darwin x86_64-apple-darwin
          cargo test --verbose --target aarch64-apple-darwin
          cargo test --verbose --target x86_64-apple-darwin
